### ISSUE TITLE
Unable to load component class org.sonar.scanner.scan.ProjectLock

### ISSUE THREAD

**Issue by roded** [musketyr/docker-sonarqube#2]
Hi,
Using the currently latest commit (a509791d3231bd4c5354a15a500a650e5d753f2b) the Sonaqube server loads fine.
However, when running the `gradle sonarqube` task, it fails due to the following message:

> Executing task ':sonarqube' (up-to-date check took 0.001 secs) due to:
>   Task has not declared any outputs.
> User cache: /home/roded/.sonar/cache
> Publish mode
> Load global settings
> Load global settings (done) | time=382ms
> Server id: F57190D6-AWb4Oxgltq7i25CM-gLN
> User cache: /home/roded/.sonar/cache
> Load/download plugins
> Load plugins index
> Load plugins index (done) | time=57ms
> Load/download plugins (done) | time=49451ms
> Loaded core extensions: 
> Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
> :sonarqube FAILED
> :sonarqube (Thread[main,5,main]) completed. Took 53.092 secs.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':sonarqube'.
> > Unable to load component class org.sonar.scanner.scan.ProjectLock
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
> 
> BUILD FAILED

Am I correct in assuming this is a Sonarqube server issue?

**Comment by roded** [comment]
After enabling stacktraces and disabling a few unneeded plugins due to missing dependencies, I've narrowed it down to the following issue:

> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sonarqube'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
>         at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
>         at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
>         at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
>         at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
>         at org.gradle.internal.Factories$1.create(Factories.java:22)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
>         at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
>         at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
>         at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
>         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
>         at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
>         at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
>         at org.gradle.launcher.Main.doAction(Main.java:33)
>         at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
>         at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
>         at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
>         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
>         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Caused by: org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: org.sonar.plugins.groovy.codenarc.CodeNarcSensor has unsatisfied dependency 'class org.sonar.plugins.groovy.foundation.GroovyFileSystem' for constructor 'public org.sonar.plugins.groovy.codenarc.CodeNarcSensor(org.sonar.api.profiles.RulesProfile,org.sonar.plugins.groovy.foundation.GroovyFileSystem)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@7734695d:167<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@348c00d9:237<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@63236968:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@484313a6:40<|
>         at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
>         at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
>         at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
>         at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
>         at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
>         at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
>         at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
>         at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
>         at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
>         at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
>         at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
>         at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:290)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.completeScannerExtensions(ScannerExtensionDictionnary.java:118)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.getExtensions(ScannerExtensionDictionnary.java:113)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.getFilteredExtensions(ScannerExtensionDictionnary.java:103)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.selectSensors(ScannerExtensionDictionnary.java:77)
>         at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:55)
>         at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
>         at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:164)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
>         at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:319)
>         at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:314)
>         at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:312)
>         at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:288)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
>         at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
>         at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:82)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
>         at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:131)
>         at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
>         at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
>         at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
>         at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
>         at com.sun.proxy.$Proxy56.execute(Unknown Source)
>         at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
>         at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
>         at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:99)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
>         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
>         ... 60 more
>
